<../../mkconfig

DIRS=\

TARG=\
	httpdial.dis\
	httpsrv.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyring.m\
	string.m\
	sys.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
